image: blang/latex:ctanfull

build:
  script:
    - cat /etc/fonts/fonts.conf
    - mkdir -p /usr/local/share/fonts/truetype
    - cp -r ./fonts/* /usr/local/share/fonts/truetype/
    - tlmgr option repository ftp://tug.org/historic/systems/texlive/2017/tlnet-final
    - tlmgr update --self
    - tlmgr install xindy
    - tlmgr search --file xindy |grep persian
    - sed -i 's/Times New Roman/Linux Libertine/g' /usr/local/texlive/2017/texmf-dist/tex/xelatex/xepersian/soul-xepersian.def
    - ./build.sh
  artifacts:
    paths:
      - "MyThesis.pdf"
