image: blang/latex

build:
  script:
    - cat /etc/fonts/fonts.conf
    - apt-get update && apt-get install fonts-linuxlibertine
    - mkdir -p /usr/local/share/fonts/truetype
    - cp -r ./fonts/* /usr/local/share/fonts/truetype/
    - sudo fc-cache -f -v
    - ./build.sh
  artifacts:
    paths:
      - "MyThesis.pdf"
