image: blang/latex

build:
  script:
    - cat /etc/fonts/fonts.conf
    - sudo apt-get update && sudo apt-get install fonts-linuxlibertine
    - mkdir -p ~/.fonts/truetype
    - cp -r ./fonts/* ~/.fonts/truetype/
    - sudo fc-cache -f -v
    - ./build.sh
  artifacts:
    paths:
      - "MyThesis.pdf"
